config/routes.rb
Rails.application.routes.draw do

  resources :comanda_produtos

  resources :produtos

  resources :comandas

  resources :mesas

  resources :funcionarios

  resources :categorias

  resources :faturamento

  post 'faturamento/index' => 'faturamento#index'

  root 'comandas#index'

end

app/models/comanda.rb
class Comanda < ActiveRecord::Base
	belongs_to :mesa
	belongs_to :funcionario

	#has_and_belongs_to_many :produtos
	has_many :comanda_produtos, :class_name => 'ComandaProduto', :dependent => :delete_all
	has_many :produtos, :through => :comanda_produtos, :class_name => 'Produto'
end

app/controllers/comandas_controller.rb
class ComandasController < ApplicationController
  before_action :set_comanda, only: [:show, :edit, :update, :destroy]

  # GET /comandas
  # GET /comandas.json
  def index
    @comandas = Comanda.all
  end

  # GET /comandas/1
  # GET /comandas/1.json
  def show
  end

  # GET /comandas/new
  def new
    @comanda = Comanda.new
  end

  # GET /comandas/1/edit
  def edit
  end

  # POST /comandas
  # POST /comandas.json
  def create
    @comanda = Comanda.new(comanda_params)

    respond_to do |format|
      if @comanda.save
        format.html { redirect_to @comanda, notice: 'Comanda criada com sucesso.' }
        format.json { render :show, status: :created, location: @comanda }
      else
        format.html { render :new }
        format.json { render json: @comanda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comandas/1
  # PATCH/PUT /comandas/1.json
  def update
    respond_to do |format|
      if @comanda.update(comanda_params)
        format.html { redirect_to @comanda, notice: 'Comanda atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @comanda }
      else
        format.html { render :edit }
        format.json { render json: @comanda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comandas/1
  # DELETE /comandas/1.json
  def destroy
    @comanda.destroy
    respond_to do |format|
      format.html { redirect_to comandas_url, notice: 'Comanda excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comanda
      @comanda = Comanda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comanda_params
      params.require(:comanda).permit(:numero, :mesa_id, :funcionario_id, :aberto)
    end
end

app/helpers/comandas_helper.rb
module ComandasHelper
end

app/views/comandas/_form.html.erb
<%= form_for(@comanda, :html => {role: "form", :class => 'form-horizontal'}) do |f| %>
  <% if @comanda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comanda.errors.count, "error") %> prohibited this comanda from being saved:</h2>

      <ul>
      <% @comanda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Número</label>
    <div class="col-sm-2">
      <%= f.number_field :numero, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Mesa (número)</label>
    <div class="col-sm-1">
      <%= f.select(:mesa_id, Mesa.all.collect {|m| [ m.numero, m.id ] }, { :include_blank => false }, :class => 'form-control') %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Funcionário</label>
    <div class="col-sm-4">
      <%= f.select(:funcionario_id, Funcionario.all.collect {|f| [ f.nome, f.id ] }, { :include_blank => false }, :class => 'form-control') %>
    </div>
  </div>  

  <div class="form-group">
    <label class="col-sm-2 control-label">Aberto</label>
    <!-- <div class="col-sm-offset-2 col-sm-10"> -->
      <div class="checkbox">
        <label>
          <%= f.check_box :aberto %>
        </label>
      </div>
    <!-- </div> -->
  </div>



  <div class="actions">
    <% if controller.action_name == "new" %>
      <%= f.submit "Criar comanda", :class => 'btn btn-default' %>
    <% else %>
      <%= f.submit "Atualizar comanda", :class => 'btn btn-default' %>
    <% end %>
  </div>
<% end %>

app/views/comandas/edit.html.erb
<h1>Editar comanda</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @comanda %> |
<%= link_to 'Voltar', comandas_path %>

app/views/comandas/index.html.erb
<h1>Lista de comandas</h1>
<div class="">
  <table class="table">
    <thead>
      <tr>
        <th>Numero</th>
        <th>Mesa</th>
        <th>Valor total</th>
        <th>Funcionario</th>
        <th>Status</th>
        <th colspan="6"></th>
      </tr>
    </thead>

    <tbody>
      <% @comandas.each do |comanda| %>
        <tr>
          <td><%= comanda.numero %></td>
          <td><%= comanda.mesa.numero %></td>
          <td><%= retornaValorComanda(comanda) %></td>
          <td><%= comanda.funcionario.nome %></td>
          <td><%= comanda.aberto ? "Aberta" : "Fechada" %></td>
          <td><%= link_to 'Visualizar', comanda, :class => 'btn btn-default' %></td>
          <td><%= link_to 'Editar', edit_comanda_path(comanda), :class => 'btn btn-default' %></td>
          <% if comanda.aberto %>
            <td><%= link_to 'Adicionar Itens', '/comanda_produtos/new?comanda_id=' + comanda.id.to_s, :class => 'btn btn-primary' %></td>
          <% end %>
          <td><td><%= link_to 'Listar Itens', '/comanda_produtos?comanda_id=' + comanda.id.to_s, :class => 'btn btn-info' %></td></td>
          <td><%= link_to 'Excluir', comanda, method: :delete, data: { confirm: 'Você tem certeza?' }, :class => 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'Nova Comanda', new_comanda_path, :class => 'btn btn-success' %>

app/views/comandas/new.html.erb
<h1>Nova comanda</h1>

<%= render 'form' %>

<%= link_to 'Voltar', comandas_path %>

app/views/comandas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @comanda.numero %>
</p>

<p>
  <strong>Mesa:</strong>
  <%= @comanda.mesa.numero %>
</p>

<p>
  <strong>Valor total:</strong>
  <%= @comanda.valor_total %>
</p>

<p>
  <strong>Funcionario:</strong>
  <%= @comanda.funcionario.nome %>
</p>

<p>
  <strong>Aberto:</strong>
  <%= @comanda.aberto %>
</p>

<%= link_to 'Editar', edit_comanda_path(@comanda), :class => 'btn btn-default' %> 
<%= link_to 'Voltar', comandas_path, :class => 'btn btn-info' %>