config/routes.rb
Rails.application.routes.draw do

  resources :comanda_produtos

  resources :produtos

  resources :comandas

  resources :mesas

  resources :funcionarios

  resources :categorias

  resources :faturamento

  post 'faturamento/index' => 'faturamento#index'

  root 'comandas#index'

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
  end

  # GET /categorias/new
  def new
    @categoria = Categoria.new
  end

  # GET /categorias/1/edit
  def edit
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: 'Categoria criada com sucesso.' }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorias/1
  # PATCH/PUT /categorias/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to @categoria, notice: 'Categoria atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria.destroy
    respond_to do |format|
      format.html { redirect_to categorias_url, notice: 'Categoria excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_params
      params.require(:categoria).permit(:nome)
    end
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/views/categorias/_form.html.erb
<%= form_for(@categoria, :html => {role: "form", :class => 'form-horizontal'}) do |f| %>
  <% if @categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
      <% @categoria.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Nome</label>
    <div class="col-sm-4">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
  </div>


  <div class="actions">
    <% if controller.action_name == "new" %>
      <%= f.submit "Criar categoria", :class => 'btn btn-default' %>
    <% else %>
      <%= f.submit "Atualizar categoria", :class => 'btn btn-default' %>
    <% end %>
  </div>
<% end %>

app/views/categorias/edit.html.erb
<h1>Editar categoria</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @categoria %> |
<%= link_to 'Voltar', categorias_path %>

app/views/categorias/index.html.erb
<h1>Lista de Categorias</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categorias.each do |categoria| %>
      <tr>
        <td><%= categoria.nome %></td>
        <td><%= link_to 'Visualizar', categoria, :class => 'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_categoria_path(categoria), :class => 'btn btn-default' %></td>
        <td><%= link_to 'Excluir', categoria, method: :delete, data: { confirm: 'Você tem certeza?' }, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Categoria', new_categoria_path, :class => 'btn btn-success' %>

app/views/categorias/new.html.erb
<h1>Nova categoria</h1>

<%= render 'form' %>

<%= link_to 'Voltar', categorias_path %>

app/views/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @categoria.nome %>
</p>

<%= link_to 'Editar', edit_categoria_path(@categoria), :class => 'btn btn-default' %> 
<%= link_to 'Voltar', categorias_path, :class => 'btn btn-info' %>