config/routes.rb
Rails.application.routes.draw do

  resources :comanda_produtos

  resources :produtos

  resources :comandas

  resources :mesas

  resources :funcionarios

  resources :categorias

  resources :faturamento

  post 'faturamento/index' => 'faturamento#index'

  root 'comandas#index'

end

app/models/produto.rb
class Produto < ActiveRecord::Base
	belongs_to :categoria

	#has_and_belongs_to_many :comandas
	has_many :comanda_produtos, :class_name => 'ComandaProduto', :dependent => :delete_all
	has_many :comandas, :through => :comanda_produtos, :class_name => 'Comanda'
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto criado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :valor, :categoria_id)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto, :html => {role: "form", :class => 'form-horizontal'}) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Nome</label>
    <div class="col-sm-2">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Valor</label>
    <div class="col-sm-2">
      <%= f.text_field :valor, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Categoria</label>
    <div class="col-sm-2">
      <%= f.select(:categoria_id, Categoria.all.collect {|c| [ c.nome, c.id ] }, { :include_blank => false }, :class => 'form-control') %>
    </div>
  </div>

  <div class="actions">
    <% if controller.action_name == "new" %>
      <%= f.submit "Criar produto", :class => 'btn btn-default' %>
    <% else %>
      <%= f.submit "Atualizar produto", :class => 'btn btn-default' %>
    <% end %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editar produto</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @produto %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<h1>Lista de produtos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Valor</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.valor %></td>
        <td><%= produto.categoria.nome %></td>
        <td><%= link_to 'Visualizar', produto, :class => 'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto), :class => 'btn btn-default' %></td>
        <td><%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Você tem certeza?' }, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_produto_path, :class => 'btn btn-success' %>

app/views/produtos/new.html.erb
<h1>Novo produto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @produto.valor %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @produto.categoria.nome %>
</p>

<%= link_to 'Editar', edit_produto_path(@produto), :class => 'btn btn-default' %> 
<%= link_to 'Voltar', produtos_path, :class => 'btn btn-info' %>