config/routes.rb
Rails.application.routes.draw do

  resources :comanda_produtos

  resources :produtos

  resources :comandas

  resources :mesas

  resources :funcionarios

  resources :categorias

  resources :faturamento

  post 'faturamento/index' => 'faturamento#index'

  root 'comandas#index'

end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionário criado com sucesso.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionário excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :telefone, :data_nascimento, :cargo)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario, :html => {role: "form", :class => 'form-horizontal'}) do |f| %>
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Nome</label>
    <div class="col-sm-4">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">CPF</label>
    <div class="col-sm-2">
      <%= f.text_field :cpf, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Telefone</label>
    <div class="col-sm-2">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Data de Nascimento</label>
    <div class="col-sm-3">
      <%= f.date_select :data_nascimento, :class => 'form-control', :start_year => 1940 %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Cargo</label>
    <div class="col-sm-3">
      <%= f.text_field :cargo, :class => 'form-control' %>
    </div>
  </div>


  <div class="actions">
    <% if controller.action_name == "new" %>
      <%= f.submit "Criar funcionário", :class => 'btn btn-default' %>
    <% else %>
      <%= f.submit "Atualizar funcionário", :class => 'btn btn-default' %>
    <% end %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editar funcionário</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @funcionario %> |
<%= link_to 'Voltar', funcionarios_path %>

app/views/funcionarios/index.html.erb
<h1>Lista de funcionários</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Telefone</th>
      <th>Data nascimento</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.cpf %></td>
        <td><%= funcionario.telefone %></td>
        <td><%= funcionario.data_nascimento.try(:strftime, "%d/%m/%Y") %></td>
        <td><%= funcionario.cargo %></td>
        <td><%= link_to 'Visualizar', funcionario, :class => 'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_funcionario_path(funcionario), :class => 'btn btn-default' %></td>
        <td><%= link_to 'Excluir', funcionario, method: :delete, data: { confirm: 'Você tem certeza?' }, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Funcionário', new_funcionario_path, :class => 'btn btn-success' %>

app/views/funcionarios/new.html.erb
<h1>Novo funcionário</h1>

<%= render 'form' %>

<%= link_to 'Voltar', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @funcionario.cpf %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @funcionario.telefone %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @funcionario.data_nascimento.try(:strftime, "%d/%m/%Y") %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @funcionario.cargo %>
</p>

<%= link_to 'Editar', edit_funcionario_path(@funcionario), :class => 'btn btn-default' %> 
<%= link_to 'Voltar', funcionarios_path, :class => 'btn btn-info' %>